kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: galera-controller
  labels:
    name: galera
spec:
  replicas: 1
  selector:
    name: galera
  template:
    metadata:
      labels:
        name: galera
    spec:
        containers:
          - name: galera
            image: jmdejager/docker-percona-galera
            ports:
              - containerPort: 3306
              - containerPort: 4444
              - containerPort: 4567
              - containerPort: 4568
            env:
              - name: PUBLISH
                key: PUBLISH
                value: "3306"
              - name: CLUSTER
                key: CLUSTER
                value: galera
              - name: ETCD_HOST
                key: ETCD_HOST
                value: 172.17.8.101
              - name: MYSQL_USER
                key: MYSQL_USER
                value: mysql
              - name: MYSQL_PASS
                key: MYSQL_PASS
                value: mysql
            volumeMounts:
              - name: database-data
                mountPath: /var/lib/mysql
        volumes:
          - name: database-data
            source:
              hostDir:
                path: /var/lib/mysql
